feat : Added new test.yml - Tested on local

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -6,17 +6,25 @@ env:
   STARKNET_FOUNDRY_VERSION: 0.12.0
 
 jobs:
-  check:
+  check1:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: software-mansion/setup-scarb@v1
         with:
           scarb-version: "2.3.1"
+      - name: Install dependencies
+        run: |
+          apt-get update
+          apt-get install -y curl
       - name: Install starknet foundry
         run: |
           curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh -s -- -v ${STARKNET_FOUNDRY_VERSION}
-          echo "/home/runner/.local/bin" >> $GITHUB_PATH
-
+          echo "/root/.local/bin" >> $GITHUB_PATH
+          echo "Listing /root/.local/bin:"
+          ls -al /root/.local/bin
       - name: Run cairo tests
-        run: snforge test
+        run: |
+          export PATH="/root/.local/bin:$PATH"
+          echo "Current PATH: $PATH"
+          /root/.local/bin/snforge test || echo "snforge not found in /root/.local/bin"
