Implemented create_with_range function (#13)
* Implemented create_with_range function

* Minor change

* feat : update test for create_with_range

* feat : Updated snforge version in yaml

* feat : Added path manually in the test.yaml

* feat : Added new test.yml - Tested on local

* feat : Removed installing dependencies from yml

* feat : Removed installing dependencies from yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,7 +3,7 @@ name: Test
 on: [push, pull_request]
 
 env:
-  STARKNET_FOUNDRY_VERSION: 0.9.1
+  STARKNET_FOUNDRY_VERSION: 0.12.0
 
 jobs:
   check:
@@ -14,6 +14,13 @@ jobs:
         with:
           scarb-version: "2.3.1"
       - name: Install starknet foundry
-        run: curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh -s -- -v ${STARKNET_FOUNDRY_VERSION}
+        run: |
+          curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh -s -- -v ${STARKNET_FOUNDRY_VERSION}
+          echo "/root/.local/bin" >> $GITHUB_PATH
+          echo "Listing /root/.local/bin:"
+          ls -al /root/.local/bin
       - name: Run cairo tests
-        run: snforge test
+        run: |
+          export PATH="/root/.local/bin:$PATH"
+          echo "Current PATH: $PATH"
+          /root/.local/bin/snforge test || echo "snforge not found in /root/.local/bin"
